# This file was generated by GoReleaser. DO NOT EDIT.
cask "fbrcm" do
  version "0.20.0"

  on_macos do
    on_arm do
      sha256 "3073f22dc3be6b55869253d364a0abcb9e2625afc1811cb6bc2ba7fc86bbd6ed"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bcd628752a3254f6ea7cc0b7b944a4ce947d081b79fc6e09884df6dc227945c2"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "09b169f4d601ad7c542f4202d54053196006edd094435ba3bc5861385fd1c22e"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "08a3416e07648469e4d3325d99b34c22aa308b701ee1d76668f37dd3738713cd"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_linux_x86_64.tar.gz"
    end
  end

  name "fbrcm"
  desc "Firebase Remote Config Management"
  homepage "https://github.com/yumauri/fbrcm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fbrcm"
  bash_completion "completions/fbrcm.bash"
  fish_completion "completions/fbrcm.fish"
  zsh_completion "completions/fbrcm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fbrcm"]
    end
  end

  # No zap stanza required
end
