# This file was generated by GoReleaser. DO NOT EDIT.
cask "fbrcm" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "b1fe9aad6101558b1b796cfe333adbe3007941d8151314f027ce7f6c92e41903"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9216dc377d7bfa771be617e2718129223a818bbf7bf8202b78f70351712279f8"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6026ccffc71d925cc17b41ad5b3e5f928399aae37ae2c008e517458bfcce4af1"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a97d5fa431c4e896e5f5af2472b3328ab6a8efa8df358f6dc4d2fe7474023761"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_linux_arm64.tar.gz"
    end
  end

  name "fbrcm"
  desc "Firebase Remote Config Management"
  homepage "https://github.com/yumauri/fbrcm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fbrcm"
  bash_completion "completions/fbrcm.bash"
  fish_completion "completions/fbrcm.fish"
  zsh_completion "completions/fbrcm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fbrcm"]
    end
  end

  # No zap stanza required

end
