# This file was generated by GoReleaser. DO NOT EDIT.
cask "fbrcm" do
  version "0.20.1"

  on_macos do
    on_arm do
      sha256 "d704175fb89db76bf9ec9ed23f8a594c3e74173e06c345d96fc287f97fce3a9c"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fbfdf696d19d6329657f4b0a106983ad999654ee0355ecfe0c6e8c6934bce319"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c75d45fc1045ee85adfc0ac3184b6d7785339b4ddfa938203c84ddf1d66c91ce"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "60364950509f1a07ee48aad01dac4927be3f3f9708fa47ed438fa8d8245eed88"
      url "https://github.com/yumauri/fbrcm/releases/download/v#{version}/fbrcm_linux_x86_64.tar.gz"
    end
  end

  name "fbrcm"
  desc "Firebase Remote Config Management"
  homepage "https://github.com/yumauri/fbrcm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fbrcm"
  bash_completion "completions/fbrcm.bash"
  fish_completion "completions/fbrcm.fish"
  zsh_completion "completions/fbrcm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fbrcm"]
    end
  end

  # No zap stanza required
end
